base_url = "https://blinsay.com"
title = "Ben Linsay"
author = "Ben Linsay"

generate_feed = true
minify_html = true
compile_sass = true
build_search_index = false

[markdown]
highlight_code = false

[extra]
header_nav = [{ name = "home", url = "/" }, { name = "posts", url = "/blog" }]
