base_url = "https://blinsay.com"
title = "ben linsay"

minify_html = true
compile_sass = true
build_search_index = false

[markdown]
highlight_code = false

[extra]
header_nav = [{ name = "home", url = "/" }, { name = "posts", url = "/blog" }]
